//
//  BibleCatalogEntry+Published.swift
//  OpenBibleAI
//

import BibleAI
import BibleDomain

extension BibleCatalogEntry {
    /// Versions published as GitHub release assets of this repository, one
    /// release per version package, pinned by size and SHA-256. Generated by
    /// `Tools/BibleImport/make_release.py` (see DEVELOPMENT.md). Only
    /// public-domain or licensed texts are published.
    static let published: [BibleCatalogEntry] = [
        published(
            id: "kjv",
            name: "King James Version",
            abbreviation: "KJV",
            language: "en",
            copyright: "Public domain",
            tag: "bible-kjv-1",
            files: [
                .init(name: "version.json", size: 127, sha256: "84bdd87765f9360354c981782177434f0623bb4b2abcd12e55f8884fe4e5cb4b"),
                .init(name: "books.json", size: 5_310, sha256: "8ee8b3d8827b880522ad35c2e235ff0d009cb990ab861233910e1925f959c3dd"),
                .init(name: "verses.json", size: 6_698_294, sha256: "53f72606c548907934bc3109d7dba2185eede224e445c70e30bd0d99cc516d69"),
                .init(name: "embeddings.bin", size: 16_080_369, sha256: "bc4e5d102ff1929bea1fa81aa6cb3f1a0ecdbafa5d0752ac1651768a49405b30"),
            ]
        ),
        published(
            id: "rv1909",
            name: "Reina-Valera 1909",
            abbreviation: "RV1909",
            language: "es",
            copyright: "Dominio público",
            tag: "bible-rv1909-1",
            files: [
                .init(name: "version.json", size: 135, sha256: "cc40ab47863d54d74a33ec7cf104d0bb73f8ac0444d14a72b5186edf2ec19c8d"),
                .init(name: "books.json", size: 5_319, sha256: "11a538fdce53452a02c93881e81390ed4c41988274d89e41a30bfce96b25a34b"),
                .init(name: "verses.json", size: 6_442_872, sha256: "2c01852455d8c3a6fb65707aec1cff1edd23d0e8bde7ba740ccac351493d8b64"),
                .init(name: "embeddings.bin", size: 16_071_063, sha256: "ba43027d0c77dcc0472629df06f5bc5ef1e7e7653caf5d3c76abded45a59dafd"),
            ]
        ),
    ]

    private static func published(
        id: String,
        name: String,
        abbreviation: String,
        language: String,
        copyright: String,
        tag: String,
        files: [ModelManifest.File]
    ) -> BibleCatalogEntry {
        do {
            return BibleCatalogEntry(
                version: try BibleVersion(id: id, name: name, abbreviation: abbreviation, languageCode: language, copyright: copyright),
                manifest: ModelManifest(repository: "mduranx64/OpenBibleAI", revision: tag, files: files, host: .gitHubRelease)
            )
        } catch {
            preconditionFailure("Invalid published Bible \(id): \(error)")
        }
    }
}
