//
//  BibleBookNames.swift
//  BibleDomain
//

/// Book names by publisher book ID, as in the import tool's tables
/// (`Tools/BibleImport/books/<language>.json`); English also names the
/// deuterocanonical books of Catholic editions. Generated answers often cite
/// a name from another language than the version's ("John" or "Juan" while
/// reading João), so citations accept every name in `aliases`. No name means
/// different books in different languages (`BibleBookNamesTests`).
public enum BibleBookNames {
    public static let english: [String: String] = [
        "GEN": "Genesis",
        "EXO": "Exodus",
        "LEV": "Leviticus",
        "NUM": "Numbers",
        "DEU": "Deuteronomy",
        "JOS": "Joshua",
        "JDG": "Judges",
        "RUT": "Ruth",
        "1SA": "1 Samuel",
        "2SA": "2 Samuel",
        "1KI": "1 Kings",
        "2KI": "2 Kings",
        "1CH": "1 Chronicles",
        "2CH": "2 Chronicles",
        "EZR": "Ezra",
        "NEH": "Nehemiah",
        "EST": "Esther",
        "JOB": "Job",
        "PSA": "Psalms",
        "PRO": "Proverbs",
        "ECC": "Ecclesiastes",
        "SOL": "Song of Solomon",
        "ISA": "Isaiah",
        "JER": "Jeremiah",
        "LAM": "Lamentations",
        "EZE": "Ezekiel",
        "DAN": "Daniel",
        "HOS": "Hosea",
        "JOE": "Joel",
        "AMO": "Amos",
        "OBA": "Obadiah",
        "JON": "Jonah",
        "MIC": "Micah",
        "NAH": "Nahum",
        "HAB": "Habakkuk",
        "ZEP": "Zephaniah",
        "HAG": "Haggai",
        "ZEC": "Zechariah",
        "MAL": "Malachi",
        "MAT": "Matthew",
        "MAR": "Mark",
        "LUK": "Luke",
        "JOH": "John",
        "ACT": "Acts",
        "ROM": "Romans",
        "1CO": "1 Corinthians",
        "2CO": "2 Corinthians",
        "GAL": "Galatians",
        "EPH": "Ephesians",
        "PHI": "Philippians",
        "COL": "Colossians",
        "1TH": "1 Thessalonians",
        "2TH": "2 Thessalonians",
        "1TI": "1 Timothy",
        "2TI": "2 Timothy",
        "TIT": "Titus",
        "PHM": "Philemon",
        "HEB": "Hebrews",
        "JAM": "James",
        "1PE": "1 Peter",
        "2PE": "2 Peter",
        "1JO": "1 John",
        "2JO": "2 John",
        "3JO": "3 John",
        "JUD": "Jude",
        "REV": "Revelation",
        "TOB": "Tobit",
        "JDT": "Judith",
        "ESG": "Esther (Greek)",
        "1MA": "1 Maccabees",
        "2MA": "2 Maccabees",
        "WIS": "Wisdom",
        "SIR": "Sirach",
        "BAR": "Baruch",
        "DNG": "Daniel (Greek)",
    ]

    public static let spanish: [String: String] = [
        "GEN": "Génesis",
        "EXO": "Éxodo",
        "LEV": "Levítico",
        "NUM": "Números",
        "DEU": "Deuteronomio",
        "JOS": "Josué",
        "JDG": "Jueces",
        "RUT": "Rut",
        "1SA": "1 Samuel",
        "2SA": "2 Samuel",
        "1KI": "1 Reyes",
        "2KI": "2 Reyes",
        "1CH": "1 Crónicas",
        "2CH": "2 Crónicas",
        "EZR": "Esdras",
        "NEH": "Nehemías",
        "EST": "Ester",
        "JOB": "Job",
        "PSA": "Salmos",
        "PRO": "Proverbios",
        "ECC": "Eclesiastés",
        "SOL": "Cantares",
        "ISA": "Isaías",
        "JER": "Jeremías",
        "LAM": "Lamentaciones",
        "EZE": "Ezequiel",
        "DAN": "Daniel",
        "HOS": "Oseas",
        "JOE": "Joel",
        "AMO": "Amós",
        "OBA": "Abdías",
        "JON": "Jonás",
        "MIC": "Miqueas",
        "NAH": "Nahúm",
        "HAB": "Habacuc",
        "ZEP": "Sofonías",
        "HAG": "Hageo",
        "ZEC": "Zacarías",
        "MAL": "Malaquías",
        "MAT": "Mateo",
        "MAR": "Marcos",
        "LUK": "Lucas",
        "JOH": "Juan",
        "ACT": "Hechos",
        "ROM": "Romanos",
        "1CO": "1 Corintios",
        "2CO": "2 Corintios",
        "GAL": "Gálatas",
        "EPH": "Efesios",
        "PHI": "Filipenses",
        "COL": "Colosenses",
        "1TH": "1 Tesalonicenses",
        "2TH": "2 Tesalonicenses",
        "1TI": "1 Timoteo",
        "2TI": "2 Timoteo",
        "TIT": "Tito",
        "PHM": "Filemón",
        "HEB": "Hebreos",
        "JAM": "Santiago",
        "1PE": "1 Pedro",
        "2PE": "2 Pedro",
        "1JO": "1 Juan",
        "2JO": "2 Juan",
        "3JO": "3 Juan",
        "JUD": "Judas",
        "REV": "Apocalipsis",
    ]

    public static let portuguese: [String: String] = [
        "GEN": "Gênesis",
        "EXO": "Êxodo",
        "LEV": "Levítico",
        "NUM": "Números",
        "DEU": "Deuteronômio",
        "JOS": "Josué",
        "JDG": "Juízes",
        "RUT": "Rute",
        "1SA": "1 Samuel",
        "2SA": "2 Samuel",
        "1KI": "1 Reis",
        "2KI": "2 Reis",
        "1CH": "1 Crônicas",
        "2CH": "2 Crônicas",
        "EZR": "Esdras",
        "NEH": "Neemias",
        "EST": "Ester",
        "JOB": "Jó",
        "PSA": "Salmos",
        "PRO": "Provérbios",
        "ECC": "Eclesiastes",
        "SOL": "Cânticos",
        "ISA": "Isaías",
        "JER": "Jeremias",
        "LAM": "Lamentações",
        "EZE": "Ezequiel",
        "DAN": "Daniel",
        "HOS": "Oseias",
        "JOE": "Joel",
        "AMO": "Amós",
        "OBA": "Obadias",
        "JON": "Jonas",
        "MIC": "Miqueias",
        "NAH": "Naum",
        "HAB": "Habacuque",
        "ZEP": "Sofonias",
        "HAG": "Ageu",
        "ZEC": "Zacarias",
        "MAL": "Malaquias",
        "MAT": "Mateus",
        "MAR": "Marcos",
        "LUK": "Lucas",
        "JOH": "João",
        "ACT": "Atos",
        "ROM": "Romanos",
        "1CO": "1 Coríntios",
        "2CO": "2 Coríntios",
        "GAL": "Gálatas",
        "EPH": "Efésios",
        "PHI": "Filipenses",
        "COL": "Colossenses",
        "1TH": "1 Tessalonicenses",
        "2TH": "2 Tessalonicenses",
        "1TI": "1 Timóteo",
        "2TI": "2 Timóteo",
        "TIT": "Tito",
        "PHM": "Filemom",
        "HEB": "Hebreus",
        "JAM": "Tiago",
        "1PE": "1 Pedro",
        "2PE": "2 Pedro",
        "1JO": "1 João",
        "2JO": "2 João",
        "3JO": "3 João",
        "JUD": "Judas",
        "REV": "Apocalipse",
    ]

    /// Every known name of each book.
    public static let aliases: [String: [String]] = [english, spanish, portuguese]
        .reduce(into: [:]) { result, table in
            for (id, name) in table { result[id, default: []].append(name) }
        }
}
