#!/bin/sh
# Writes OpenBibleAI/Generated/BuildSettings.swift (gitignored): build settings
# the app reads at run time, from Config/Shared.xcconfig and the optional
# Config/Local.xcconfig.
#
# Xcode runs this as the app target's "Generate build settings" phase (the
# values come from the build environment). After a fresh clone, run it once
# before the first build, because Xcode lists the files to compile before
# the phase creates this one:
#
#     Tools/generate_build_settings.sh
#
# Only public values belong here: the generated file ships inside the app.
set -eu
root=$(cd "$(dirname "$0")/.." && pwd)
output="$root/OpenBibleAI/Generated/BuildSettings.swift"

# Outside Xcode, read the settings from the xcconfig files (Local overrides
# Shared, as the #include does). Values are simple `KEY = value` lines.
setting() {
  name=$1
  eval "value=\${$name-}"
  if [ -z "${ACTION-}" ]; then
    value=""
    for file in "$root/Config/Shared.xcconfig" "$root/Config/Local.xcconfig"; do
      [ -f "$file" ] || continue
      line=$(grep -E "^[[:space:]]*$name[[:space:]]*=" "$file" | tail -1 || true)
      [ -n "$line" ] && value=$(printf '%s' "${line#*=}" | sed -e 's#//.*##' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
    done
  fi
  # Swift string literal: escape backslashes and quotes.
  printf '%s' "$value" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

repository=$(setting BIBLE_RELEASE_REPOSITORY)
tag=$(setting BIBLE_RELEASE_TAG)
key=$(setting BIBLE_CATALOG_PUBLIC_KEY)
content=$(
  echo '// Generated by Tools/generate_build_settings.sh from Config/*.xcconfig.'
  echo '// Do not edit or commit; it is rewritten on every build.'
  echo ''
  echo '/// Build settings the app reads at run time (public values only).'
  echo 'nonisolated enum BuildSettings {'
  echo '    /// BIBLE_RELEASE_REPOSITORY: the GitHub repository whose release hosts the Bibles.'
  echo "    static let bibleReleaseRepository = \"$repository\""
  echo '    /// BIBLE_RELEASE_TAG: that release'"'"'s tag.'
  echo "    static let bibleReleaseTag = \"$tag\""
  echo '    /// BIBLE_CATALOG_PUBLIC_KEY: hex Ed25519 public key of the catalog, or empty.'
  echo "    static let bibleCatalogPublicKey = \"$key\""
  echo '}'
)

mkdir -p "$(dirname "$output")"
# Rewrite only on change, so unchanged settings don't trigger a recompile.
if [ ! -f "$output" ] || [ "$(cat "$output")" != "$content" ]; then
  printf '%s\n' "$content" > "$output"
fi

# In Xcode, record the xcconfig files as dependencies so changing the key in
# Local.xcconfig reruns this phase.
if [ -n "${ACTION-}" ] && [ -n "${DERIVED_FILE_DIR-}" ]; then
  mkdir -p "$DERIVED_FILE_DIR"
  dependencies="$root/Config/Shared.xcconfig"
  [ -f "$root/Config/Local.xcconfig" ] && dependencies="$dependencies $root/Config/Local.xcconfig"
  printf '%s: %s\n' "$output" "$dependencies" > "$DERIVED_FILE_DIR/BuildSettings.d"
fi
